name: elnozom
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  dio: ^3.0.10
  flutter: 
    sdk: flutter
  flutter_config: ^2.0.0
  autocomplete_textfield: ^1.7.3
  flutter_typeahead: ^3.1.3
  get_storage: ^2.0.2
  date_format: ^2.0.3
  flutter_form_builder: ^6.0.1
  simple_autocomplete_formfield: ^0.3.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 

  uses-material-design: true

  assets:
    - assets/home-bg.png
    - assets/logo.png

  fonts:
    - family: Frutiger
      fonts:
        - asset: assets/Frutiger.ttf


